### ISSUE TITLE
Banner Ads Distorted

### ISSUE THREAD

**Issue by chaseyall** [polydes/unityads#1]
When testing on an iPhone 11 device, the test ads do not display properly. They either display as a thin black line at the top, or they display as a heavily distorted advertisement at the bottom (I have all my banners programmed for the bottom). Sometimes, they will switch back and forth between these two options. Additionally, they do not always hide themselves when programmed too, particularly if the black line is the one displaying opposed to the distorted ad.

**Comment by justin-espedal** [comment]
This was fixed by ee0dcaccdd069e5d2bfe7635751a7fab0fc646ee
